### ISSUE TITLE
sample modal

### ISSUE THREAD

**Issue by mlselegant** [yubarajshrestha/laravel-module#2]
please add one sample model (with minimum default code) inside YModules.
eg:
Blog
   Controllers
       BlogController.php
   Models
       Blog.php
   Views
       index.blade.php

**Comment by yubarajshrestha** [comment]
You have provided backend panel there. Please execute command `php artisan serve` and then visit `your-server/ym`. From there create any new modules for eg. Blog and all things will be setup automatically there... 👍

**Comment by mlselegant** [comment]
QueryException in Connection.php line 770:
SQLSTATE[HY000] [1045] Acc�s refus� pour l'utilisateur: 'homestead'@'@localhost' (mot de passe: OUI) (SQL: select * from `modularize`)


Do we need to create table modularize  in DB???

**Comment by yubarajshrestha** [comment]
As shown in `readme.md` you have to migrate database and it automatically creates one table for you. This is helpful to check the lists of your modules from backend. It'll be easy for you to remove any modules that you don't want from backend so easy.

**Comment by mlselegant** [comment]
Done

**Comment by yubarajshrestha** [comment]
Awesome!
